version: '3.9'
services:
  backend:
    image: haseeb012/mern-backend:latest
    container_name: mern-backend
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:5000:5000'
    networks:
      - mern-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    image: haseeb012/mern-frontend:latest
    container_name: mern-frontend
    restart: always
    ports:
      - '127.0.0.1:5173:80'
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
